export const USER_SIGNIN = 'USER_SIGNIN'

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'

export const SIGNIN_FAILED = 'SIGNIN_FAILED'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAILED = 'UPDATED_FAILED'
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LOGOUT = 'LOGOUT'